### ISSUE TITLE
SSL error - self signed certs

### ISSUE THREAD

**Issue by thebetterjort** [evry/docker-oidc-proxy#10]
openidc.lua:486: failed: 18: self signed certificate, client: 172.24.0.1, server: _, request: "GET / HTTP/1.1", host: "localhost:9099"
```
version: '3'

services:
  fathom:
    image: usefathom/fathom:latest
    command: ./fathom --config=/config/.env server
    depends_on:
      - postgres_fathom
    volumes:
      - ./fathom.env:/config/.env
    ports:
      - 8446:8080

  postgres_fathom:
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgresql/data
      - db_data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/fathom
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  nginx_openid:
    image: "evry/oidc-proxy"
    environment: 
      - OID_DISCOVERY=https://tharpool.winad.arwd.circ8.dcn:8444/auth/realms/master/protocol/openid-connect/auth
      - OID_CLIENT_ID=nginx
      - OID_CLIENT_SECRET=0fd32218-8e31-45ac-8b53-d6b523ab99b6
      - PROXY_HOST=fathom
      - PROXY_PORT=8446
      - PROXY_PROTOCOL=https
      - OID_SESSION_CHECK_SSI=off
      - OID_SESSION_NAME=oidc_auth
      - OID_REDIRECT_PATH=/redirect_uri
    ports:
     - "9099:80"
```
